import { Cart } from '../modules/cart/classes/cart.model';
import { CartItem } from '../modules/cart/classes/cart-item.model';
import { Product } from '../modules';
import { CartRequest } from '@congacommerce/ecommerce';
import { ACCOUNT } from 'projects/congacommerce/elements/src/lib/price-summary/test/data';


/**
 * @ignore
 */
export const CART_ITEMS = [
    {
        "LineType": "Product/Service",
        "IsTaxable": false,
        "LineNumber": 1,
        "HasOptions": false,
        "PrimaryLineNumber": 1,
        "Frequency": "One Time",
        "Name": "LI-0000881660",
        "Configuration": {
            "Id": ""
        },
        "Quantity": 1,
        "StartDate": "2022-06-15",
        "CreatedById": "005R0000005OT2UIAW",
        "ConfigStatus": "NA",
        "EndDate": "2022-06-15",
        "CurrencyIsoCode": "USD",
        "Product": {
            "Id": "01t2h000002BFwpAAG"
        },
        "Id": "a1379000000SUYlAAO",
        "SellingTerm": 1,
        "IsOptionRollupLine": false,
        "ConstraintCheckStatus": "NA",
        "IsPrimaryLine": true,
        "HasAttributes": true,
        "ProductVersion": 1,
        "PricingStatus": "Pending",
        "LineStatus": "New",
        "ItemSequence": 1,
        "PriceList": {
            "Id": "a171T000005il1XQAQ"
        }
    },
    {
        "LineType": "Option",
        "IsTaxable": true,
        "LineNumber": 1,
        "HasOptions": false,
        "PrimaryLineNumber": 1,
        "Frequency": "One Time",
        "Name": "LI-0000875660",
        "Configuration": {
            "Id": ""
        },
        "Quantity": 1,
        "StartDate": "2022-06-15",
        "CreatedById": "005R0000098UR2UIAW",
        "ConfigStatus": "NA",
        "EndDate": "2022-06-15",
        "Product": {
            "Id": "01t2h000002BFwpAAG"
        },
        "Id": "a1379000000SUYlAAO",
        "SellingTerm": 1,
        "IsOptionRollupLine": false,
        "ConstraintCheckStatus": "NA",
        "IsPrimaryLine": true,
        "HasAttributes": true,
        "ProductVersion": 1,
        "PricingStatus": "Pending",
        "LineStatus": "New",
        "ItemSequence": 1,
        "PriceList": {
            "Id": "a171T000005il1XQAQ"
        }
    },
    {
        "AddedBy": "User",
        "Configuration": {
            "Id": "72b194e9-3992-49ba-ae06-ea62f301f998",
            "Name": "72b194e9-3992-49ba-ae06-ea62f301f998"
        },
        "PriceList": {
            "Id": "cbc75112-60e9-47b2-a632-f70d5912b70f",
            "Name": "Tier 1 Hardware & Software"
        },
        "PrimaryLineNumber": 1,
        "Product": {
            "Id": "f5d33c74-4079-49a1-89cf-41394f47e8a1",
        },
        "Currency": "USD",
        "Id": "a25c72ab-24d5-40fd-baff-4b779a02076f",
        "Name": "DL160 Gen8 Default Support"
    },
] as Array<CartItem>;


/**
 * @ignore
 */
export const CART = {
    "Id": "a1I790000007VdqEAE",
    "OwnerId": "005R0000005OT2UIAW",
    "IsDeleted": false,
    "Name": "a1I790000007Vdq",
    "CurrencyIsoCode": "USD",
    "AccountId": "0011900000hnGsrAAE",
    "BusinessObjectId": "a3K79000002DeHQEA0",
    "BusinessObjectType": "Digital Commerce",
    "IsPricePending": false,
    "IsTransient": true,
    "PriceListId": "a171T000005il1XQAQ",
    "Status": "New",
    "SummaryGroups__r": ""
} as unknown as Cart;

export const TRANSLATION_EN_US = [
    {
        "ERROR": {
            "OPTION_GROUP": {
                "ERROR": "Option Group Errors",
                "MIN_OPTIONS": "You must select at least {{value}} options.",
                "MAX_OPTIONS": "You can select no more than {{value}} options.",
                "MIN_TOTAL_QUANTITY": "The total minimum quantity is {{value}}.",
                "MAX_TOTAL_QUANTITY": "The total maximum quantity is {{value}}.",
                "REQUIRED_OPTION_MISSING": "Option(s) {{value}} is/are required."
            },
            "UNABLE_TO_RENEW": "An error occurred renewing this asset(s)",
            "CART": {
                "TOO_MANY_ATTEMPTS": "An item in your cart could not be priced. Please try removing an item / items and try again.",
                "SERVER_ERROR": "Oops something went wrong.",
                "PRICE_CHANGE": "The price of your cart has been updated",
                "PRICE_CHANGE_TOASTR_TITLE": "Price Update",
                "VALIDATE": "There are errors in your cart.",
                "CONSTRAINT_RULES": "An item in your cart violated 1 or more constraint rules."
            },
            "CART_ITEM": {
                "VALIDATE": "The are errors with this cart item."
            },
            "CONSTRAINT_RULE": {
                "ASSOCIATE_AND_APPLY": "An error ocurred getting the constraint rules for your cart."
            },
            "PROMOTION": {
                "PROMOTION_OR_COUPON_NOT_AVAILABLE": "Promotion {{name}} could not be applied.",
                "INVALID_PROMOTION_TITLE": "Promotion Not Applied",
                "INVALID_COUPON_TITLE": "Coupon Not Applied",
                "COUPON_CODE_EXPIRED": "Coupon {{name}} is expired.",
                "INACTIVE_COUPON_CODE": "Coupon {{name}} is not valid.",
                "COUPON_LIMIT_EXCEEDED": "Coupon {{name}} usage limit is exceeded",
                "TABLE_COL_OPTION": "Option"
            },
            "APPLICATION_ERROR_TOASTR_TITLE": "Application Error",
            "INVALID_QUANTITY": "Cannot add a quantity less than 1"
        },
        "SUCCESS": {
            "TITLE": "Success",
            "CART": {
                "ITEM_ADDED_TOASTR_MESSAGE": "{{productName}} was added to the cart.",
                "ITEM_ADDED_TOASTR_TITLE": "Item Added",
                "CONFIGURATION_UPDATED": "{{productName}} configuration has been updated."
            },
            "PROMOTION": {
                "VALID_PROMOTION_TITLE": "Promotion Applied",
                "VALID_PROMOTION_MESSAGE": "Promotion {{name}} is applied successfully",
                "REMOVED_TOASTR_MESSAGE": "Promotion {{name}} has been removed.",
                "REMOVED_TOASTR_TITLE": "Promotion Removed"
            },
            "QUOTE_UPDATED": "Quote Updated Successfully!",
            "QUOTE_UPDATE_TITLE": "Quote Update",
            "GENERATED": "Your order document has been generated and can be viewed under the 'Attachments' tab.",
            "DOCUMENT_GENERATED_TITLE": "Document Generated",
            "PRESENTED": "Your order document has been presented to {{primary_contact}} and email notification is sent out.",
            "DOCUMENT_PRESENTED_TITLE": "Document Presented",
            "FAVORITE": {
                "TITLE": "Favorite items added!",
                "ADD_FAVORITE": "Added new {{name}} Favorite.",
                "UPDATE_FAVORITE": "Updated existing {{name}} Favorite",
                "ADD_FAVORITE_TO_CART": "Items from {{name}} were added to the cart."
            }
        },
        "INFO": {
            "TITLE": "Info",
            "GENERATE_INFO": "Your order document is being generated. You will get notified when its ready."
        }
    }
]

export const TRANSLATED_DATA =
{
    "ERROR": {
        "OPTION_GROUP": {
            "ERROR": "Option Group Errors",
            "MIN_OPTIONS": "You must select at least {{value}} options.",
            "MAX_OPTIONS": "You can select no more than {{value}} options.",
            "MIN_TOTAL_QUANTITY": "The total minimum quantity is {{value}}.",
            "MAX_TOTAL_QUANTITY": "The total maximum quantity is {{value}}.",
            "REQUIRED_OPTION_MISSING": "Option(s) {{value}} is/are required."
        },
        "UNABLE_TO_RENEW": "An error occurred renewing this asset(s)",
        "CART": {
            "TOO_MANY_ATTEMPTS": "An item in your cart could not be priced. Please try removing an item / items and try again.",
            "SERVER_ERROR": "Oops something went wrong.",
            "PRICE_CHANGE": "The price of your cart has been updated",
            "PRICE_CHANGE_TOASTR_TITLE": "Price Update",
            "VALIDATE": "There are errors in your cart.",
            "CONSTRAINT_RULES": "An item in your cart violated 1 or more constraint rules."
        },
        "CART_ITEM": {
            "VALIDATE": "The are errors with this cart item."
        },
        "CONSTRAINT_RULE": {
            "ASSOCIATE_AND_APPLY": "An error ocurred getting the constraint rules for your cart."
        },
        "PROMOTION": {
            "PROMOTION_OR_COUPON_NOT_AVAILABLE": "Promotion {{name}} could not be applied.",
            "INVALID_PROMOTION_TITLE": "Promotion Not Applied",
            "INVALID_COUPON_TITLE": "Coupon Not Applied",
            "COUPON_CODE_EXPIRED": "Coupon {{name}} is expired.",
            "INACTIVE_COUPON_CODE": "Coupon {{name}} is not valid.",
            "COUPON_LIMIT_EXCEEDED": "Coupon {{name}} usage limit is exceeded",
            "TABLE_COL_OPTION": "Option"
        },
        "APPLICATION_ERROR_TOASTR_TITLE": "Application Error",
        "INVALID_QUANTITY": "Cannot add a quantity less than 1"
    }
}


export const PRODUCT = {
    "Id": "42a04524-3692-4cba-b0e4-961c65e46d60",
    "Name": "BL660c Gen8 Server Blade",
    "ConfigurationType": "Bundle",
    "Description": "BL660c Gen8 Server series is ideal for virtualization, database, business processing, and general 4P data-intensive applications where fine-tuning of data center space and price/performance is paramount.",
    "Family": "Hardware",
    "ProductCode": "HW-BL004"
} as Product;


export const CART_REQUEST = [{
    "PrimaryTxnLineNumber": 2,
    "ExternalId": "26155c28",
    "ProductId": "01t2h000002BFwpAAG",
    "Quantity": 1,
    "LineType": "Product/Service",
    "PricingStatus": "Pending"
}] as Array<CartRequest>


const CART_INFO = new Cart()

CART_INFO.Id = "a1I790000007VdqEAE";
CART_INFO.Name = "a1I790000007Vdq";
CART_INFO.Account = ACCOUNT;
CART_INFO.BusinessObjectId = "a3K79000002DeHQEA0";
CART_INFO.BusinessObjectType = "Digital Commerce";
CART_INFO.IsPricePending = false;
CART_INFO.IsTransient = true;
CART_INFO.Status = "New";

export { CART_INFO }

export const CART_ITEMS_BY_ID = {
    "Cart": {
        "Account": {
            "Id": "c1d05a85-26b9-4033-b698-2b8f51e96b2d",
            "Name": "Alpha Corporation"
        },
        "Ancestor": null,
        "ApprovalStatus": null,
        "BaseRelationCount": null,
        "BillingPreference": null,
        "BillToAccount": null,
        "BusinessObjectId": null,
        "BusinessObjectProfile": "Regular",
        "BusinessObjectRefId": null,
        "BusinessObjectType": "Agreement",
        "Comments": null,
        "ContractNumbers": null,
        "CostRollupInfo": null,
        "CouponCodes": null,
        "CurrentUser": null,
        "Description": null,
        "EffectiveDate": "2022-09-20T03:52:35",
        "EffectivePriceList": {
            "Id": "cbc75112-60e9-47b2-a632-f70d5912b70f",
            "Name": "Tier 1 Hardware & Software"
        },
        "ExpectedEndDate": null,
        "ExpectedStartDate": "2022-09-20T00:00:00",
        "FinalizedDate": null,
        "Intent": null,
        "IsPricePending": false,
        "IsTaskPending": false,
        "IsTransient": true,
        "IsValidationPending": false,
        "LineItemsAwaitingPrice": null,
        "LegalEntity": null,
        "Location": null,
        "NumberOfItems": 0,
        "Order": null,
        "ParentConfiguration": null,
        "PaymentTerm": null,
        "PriceList": {
            "Id": "cbc75112-60e9-47b2-a632-f70d5912b70f",
            "Name": "Tier 1 Hardware & Software"
        },
        "PricingDate": "2022-09-20T03:52:35",
        "Primordial": null,
        "PurchaseId": null,
        "RenewalAdjustmentAmount": null,
        "RenewalAdjustmentType": null,
        "ShipToAccount": null,
        "SplitCriteriaKey": null,
        "Status": "New",
        "SummaryGroupType": "Category",
        "TaskCompletedDate": null,
        "UseType": "Main",
        "VersionNumber": null,
        "ActivationDate": null,
        "Id": "10037a9e-d5fd-4d23-bca5-999cd4e274ca",
        "Name": "10037a9e-d5fd-4d23-bca5-999cd4e274ca",
        "CreatedBy": {
            "Id": "d717a075-9cbf-480c-b230-837e0e6dee75",
            "Name": "TestUser1 User"
        },
        "CreatedDate": "2022-09-20T03:52:35",
        "ModifiedBy": {
            "Id": "d717a075-9cbf-480c-b230-837e0e6dee75",
            "Name": "TestUser1 User"
        },
        "ModifiedDate": "2022-09-20T03:52:37",
        "ExternalId": null,
        "PDTest_CustomField_c": "Custom Field Default Value",
        "ActivationDate_c": null
    },
    "LineItems": [
        {
            "AddedBy": "User",
            "AddedByRuleInfo": null,
            "AdHocGroup": null,
            "AdjustedPrice": null,
            "AdjustmentAmount": null,
            "AdjustmentType": null,
            "AllocateGroupAdjustment": true,
            "AllowableAction": "Unrestricted",
            "AllowManualAdjustment": true,
            "AllowProration": false,
            "AllowRemoval": true,
            "Asset": null,
            "AssetLineItem": null,
            "AssetQuantity": null,
            "Attribute": null,
            "AutoRenewalTerm": null,
            "AutoRenewalType": null,
            "BaseCost": null,
            "BaseCostOverride": null,
            "BaseExtendedCost": null,
            "BaseExtendedPrice": null,
            "BasePrice": null,
            "BasePriceMethod": null,
            "BasePriceOverride": null,
            "BaseProduct": null,
            "BillingFrequency": null,
            "BillingPreference": null,
            "BillingRule": null,
            "BillToAccount": null,
            "Category": null,
            "CategoryHierarchyIds": null,
            "ChargeType": null,
            "ClassificationHierarchyInfo": null,
            "CollaborationParentLineNumber": null,
            "Comments": "The HP ProLiant DL380e Gen8 sets the next generation standards of 2U 2-socket rack servers for the industry. With enhanced configuration flexibility, unmatched performance, and leading energy efficient design the DL380e Gen8 offers the perfect solution for the dynamic compute and storage requirements of today's demanding datacenters.",
            "CommitmentQuantity": null,
            "ConfigStatus": null,
            "Configuration": {
                "Id": "10037a9e-d5fd-4d23-bca5-999cd4e274ca",
                "Name": "10037a9e-d5fd-4d23-bca5-999cd4e274ca"
            },
            "ConstraintCheckStatus": null,
            "ContractNumbers": null,
            "CopySourceBundleNumber": null,
            "CopySourceLineNumber": null,
            "CopySourceNumber": null,
            "Cost": null,
            "CouponCode": null,
            "DeltaPrice": null,
            "DeltaQuantity": null,
            "DerivedFrom": null,
            "Description": "The HP ProLiant DL380e Gen8 sets the next generation standards of 2U 2-socket rack servers for the industry. With enhanced configuration flexibility, unmatched performance, and leading energy efficient design the DL380e Gen8 offers the perfect solution for the dynamic compute and storage requirements of today's demanding datacenters.",
            "EndDate": null,
            "ExtendedCost": null,
            "ExtendedDescription": null,
            "ExtendedPrice": null,
            "ExtendedQuantity": null,
            "FlatOptionPrice": null,
            "Frequency": "One Time",
            "GroupAdjustmentPercent": null,
            "Guidance": null,
            "HasAttributes": false,
            "HasBaseProduct": false,
            "HasDefaults": false,
            "HasIncentives": false,
            "HasOptions": false,
            "HasTieredPrice": false,
            "HideCopyAction": false,
            "HideInvoiceDisplay": false,
            "Incentive": null,
            "IncentiveAdjustmentAmount": null,
            "IncentiveBasePrice": null,
            "IncentiveCode": null,
            "IncentiveExtendedPrice": null,
            "IncentiveType": null,
            "IsAssetPricing": false,
            "IsAutoRenew": false,
            "IsCustomizable": true,
            "IsCustomPricing": false,
            "IsHidden": false,
            "IsOptional": false,
            "IsOptionRollupLine": false,
            "IsPrimaryLine": true,
            "IsPrimaryRampLine": false,
            "IsQuantityModifiable": true,
            "IsReadOnly": false,
            "IsSellingTermReadOnly": false,
            "IsTaxable": false,
            "IsTaxInclusive": false,
            "IsUsageTierModifiable": false,
            "ItemSequence": 1,
            "LineNumber": 1,
            "LineSequence": null,
            "LineStatus": "New",
            "LineType": "Product/Service",
            "ListPrice": null,
            "Location": null,
            "MaxPrice": null,
            "MaxUsageQuantity": null,
            "MinMaxPriceAppliesTo": null,
            "MinPrice": null,
            "MinUsageQuantity": null,
            "NetAdjustmentPercent": null,
            "NetPrice": null,
            "NetUnitPrice": null,
            "Option": null,
            "OptionCost": null,
            "OptionGroupLabel": null,
            "OptionPrice": null,
            "OrderLineStatus": null,
            "ParentBundleNumber": null,
            "PaymentTerm": null,
            "PriceAdjustment": null,
            "PriceAdjustmentAmount": null,
            "PriceAdjustmentAppliesTo": null,
            "PriceAdjustmentType": null,
            "PriceGroup": null,
            "PriceIncludedInBundle": false,
            "PriceList": {
                "Id": "cbc75112-60e9-47b2-a632-f70d5912b70f",
                "Name": "Tier 1 Hardware & Software"
            },
            "PriceListItem": null,
            "PriceMethod": null,
            "PriceType": null,
            "PriceUom": null,
            "PricingDate": null,
            "PricingGuidance": null,
            "PricingStatus": "Pending",
            "PricingSteps": null,
            "PrimaryLineNumber": 1,
            "Product": {
                "Id": "42157ac3-abb1-457e-88bb-4647144039e2",
                "Name": "DL380e Gen8 Entry Level"
            },
            "ProductOption": null,
            "ProductVersion": null,
            "Quantity": 1,
            "RelatedAdjustmentAmount": null,
            "RelatedAdjustmentAppliesTo": null,
            "RelatedAdjustmentType": null,
            "RelatedItem": null,
            "RelatedPercent": null,
            "RelatedPercentAppliesTo": null,
            "RenewalAdjustmentAmount": null,
            "RenewalAdjustmentType": null,
            "RollupPriceMethod": null,
            "RollupPriceToBundle": true,
            "SellingFrequency": "One Time",
            "SellingTerm": null,
            "SellingUom": null,
            "ServiceLocation": null,
            "ShipToAccount": null,
            "StartDate": null,
            "StatusDetails": null,
            "SummaryGroup": null,
            "SyncStatus": "Pending",
            "TaxCode": null,
            "Term": null,
            "TotalQuantity": null,
            "TransferPriceLineItem": null,
            "UnitCostAdjustment": null,
            "UnitPriceAdjustmentAuto": null,
            "UnitPriceAdjustmentManual": null,
            "Uom": "Each",
            "Currency": "USD",
            "Id": "02b215a2-2523-46c9-bbd9-3d9719991fcd",
            "Name": "DL380e Gen8 Entry Level",
            "CreatedBy": {
                "Id": "d717a075-9cbf-480c-b230-837e0e6dee75",
                "Name": "TestUser1 User"
            },
            "CreatedDate": "2022-09-20T08:48:58",
            "ModifiedBy": {
                "Id": "d717a075-9cbf-480c-b230-837e0e6dee75",
                "Name": "TestUser1 User"
            },
            "ModifiedDate": "2022-09-20T08:48:58",
            "ExternalId": "5ea23702"
        }
    ],
    "SummaryGroups": null,
    "Watermark": "123"
}

export const CART_ITEM_MOCK_DATA = [
    {
        "AddedBy": "User",
        "AddedByRuleInfo": null,
        "AdHocGroup": null,
        "AdjustedPrice": null,
        "AdjustmentAmount": null,
        "AdjustmentType": null,
        "AllocateGroupAdjustment": true,
        "AllowableAction": "Unrestricted",
        "AllowManualAdjustment": true,
        "AllowProration": false,
        "AllowRemoval": true,
        "Asset": null,
        "AssetLineItem": null,
        "AssetQuantity": null,
        "Attribute": null,
        "AutoRenewalTerm": null,
        "AutoRenewalType": null,
        "BaseCost": null,
        "BaseCostOverride": null,
        "BaseExtendedCost": null,
        "BaseExtendedPrice": null,
        "BasePrice": null,
        "BasePriceMethod": null,
        "BasePriceOverride": null,
        "BaseProduct": null,
        "BillingFrequency": null,
        "BillingPreference": null,
        "BillingRule": null,
        "BillToAccount": null,
        "Category": null,
        "CategoryHierarchyIds": null,
        "ChargeType": null,
        "ClassificationHierarchyInfo": null,
        "CollaborationParentLineNumber": null,
        "Comments": "The HP ProLiant DL380e Gen8 sets the next generation standards of 2U 2-socket rack servers for the industry. With enhanced configuration flexibility, unmatched performance, and leading energy efficient design the DL380e Gen8 offers the perfect solution for the dynamic compute and storage requirements of today's demanding datacenters.",
        "CommitmentQuantity": null,
        "ConfigStatus": null,
        "Configuration": {
            "Id": "10037a9e-d5fd-4d23-bca5-999cd4e274ca",
            "Name": "10037a9e-d5fd-4d23-bca5-999cd4e274ca"
        },
        "ConstraintCheckStatus": null,
        "ContractNumbers": null,
        "CopySourceBundleNumber": null,
        "CopySourceLineNumber": null,
        "CopySourceNumber": null,
        "Cost": null,
        "CouponCode": null,
        "DeltaPrice": null,
        "DeltaQuantity": null,
        "DerivedFrom": null,
        "Description": "The HP ProLiant DL380e Gen8 sets the next generation standards of 2U 2-socket rack servers for the industry. With enhanced configuration flexibility, unmatched performance, and leading energy efficient design the DL380e Gen8 offers the perfect solution for the dynamic compute and storage requirements of today's demanding datacenters.",
        "EndDate": null,
        "ExtendedCost": null,
        "ExtendedDescription": null,
        "ExtendedPrice": null,
        "ExtendedQuantity": null,
        "FlatOptionPrice": null,
        "Frequency": "One Time",
        "GroupAdjustmentPercent": null,
        "Guidance": null,
        "HasAttributes": false,
        "HasBaseProduct": false,
        "HasDefaults": false,
        "HasIncentives": false,
        "HasOptions": false,
        "HasTieredPrice": false,
        "HideCopyAction": false,
        "HideInvoiceDisplay": false,
        "Incentive": null,
        "IncentiveAdjustmentAmount": null,
        "IncentiveBasePrice": null,
        "IncentiveCode": null,
        "IncentiveExtendedPrice": null,
        "IncentiveType": null,
        "IsAssetPricing": false,
        "IsAutoRenew": false,
        "IsCustomizable": true,
        "IsCustomPricing": false,
        "IsHidden": false,
        "IsOptional": false,
        "IsOptionRollupLine": false,
        "IsPrimaryLine": true,
        "IsPrimaryRampLine": false,
        "IsQuantityModifiable": true,
        "IsReadOnly": false,
        "IsSellingTermReadOnly": false,
        "IsTaxable": false,
        "IsTaxInclusive": false,
        "IsUsageTierModifiable": false,
        "ItemSequence": 1,
        "LineNumber": 1,
        "LineSequence": null,
        "LineStatus": "New",
        "LineType": "Product/Service",
        "ListPrice": null,
        "Location": null,
        "MaxPrice": null,
        "MaxUsageQuantity": null,
        "MinMaxPriceAppliesTo": null,
        "MinPrice": null,
        "MinUsageQuantity": null,
        "NetAdjustmentPercent": null,
        "NetPrice": null,
        "NetUnitPrice": null,
        "Option": null,
        "OptionCost": null,
        "OptionGroupLabel": null,
        "OptionPrice": null,
        "OrderLineStatus": null,
        "ParentBundleNumber": null,
        "PaymentTerm": null,
        "PriceAdjustment": null,
        "PriceAdjustmentAmount": null,
        "PriceAdjustmentAppliesTo": null,
        "PriceAdjustmentType": null,
        "PriceGroup": null,
        "PriceIncludedInBundle": false,
        "PriceList": {
            "Id": "cbc75112-60e9-47b2-a632-f70d5912b70f",
            "Name": "Tier 1 Hardware & Software"
        },
        "PriceListItem": null,
        "PriceMethod": null,
        "PriceType": null,
        "PriceUom": null,
        "PricingDate": null,
        "PricingGuidance": null,
        "PricingStatus": "Pending",
        "PricingSteps": null,
        "PrimaryLineNumber": 1,
        "Product": {
            "Id": "42157ac3-abb1-457e-88bb-4647144039e2",
            "CreatedDate": null,
            "ModifiedDate": null,
            "LastModifiedById": null,
            "CreatedById": null,
            "IconId": "https://apttussecommunities-17106240894.force.com/ecomm/servlet/servlet.FileDownload?file=00P3h0000023Z6bEAE",
            "Name": "DL380e Gen8 Entry Level",
            "ConfigurationType": "Standalone",
            "Uom": "Each",
            "Description": "The HP ProLiant DL380e Gen8 sets the next generation standards of 2U 2-socket rack servers for the industry. With enhanced configuration flexibility, unmatched performance, and leading energy efficient design the DL380e Gen8 offers the perfect solution for the dynamic compute and storage requirements of today's demanding datacenters.",
            "Family": "Hardware",
            "ProductCode": "HW-DL009",
            "IsActive": true,
            "HasAttributes": false,
            "HasDefaults": false,
            "HasOptions": false,
            "ExpirationDate": "2100-12-31T00:00:00Z",
            "EffectiveStartDate": null,
            "EffectiveDate": "1900-01-01T00:00:00Z",
            "Version": 1,
            "Categories": null,
            "PriceLists": [
                {
                    "Id": "da8a63d4-15cf-406b-9bfa-ad96bb0f0363",
                    "CreatedDate": "2022-08-11T15:35:44Z",
                    "ModifiedDate": "2022-08-30T15:48:59Z",
                    "CreatedById": "ddfec712-8827-4684-8287-1373e4f1f43d",
                    "ExpirationDate": "2100-12-31T00:00:00Z",
                    "EffectiveDate": "1900-01-01T00:00:00Z",
                    "ContractPrice": null,
                    "ListPrice": 2381,
                    "Active": true,
                    "PriceList": {
                        "Id": "cbc75112-60e9-47b2-a632-f70d5912b70f",
                        "BasedOnAdjustmentAmount": 0,
                        "BasedOnAdjustmentType": null,
                        "Name": "Tier 1 Hardware & Software",
                        "Currency": "USD",
                        "Active": true,
                        "EffectiveDate": "1900-01-01T00:00:00Z",
                        "ExpirationDate": "2100-12-31T00:00:00Z",
                        "ContractNumber": null,
                        "Description": null,
                        "DisableCurrencyAdjustment": false,
                        "Type": "Standard"
                    },
                    "PriceUom": "Each",
                    "PriceMethod": "Per Unit",
                    "Frequency": null,
                    "ChargeType": "Standard Price",
                    "PriceType": "One Time",
                    "DefaultSellingTerm": 0,
                    "DefaultQuantity": null,
                    "Sequence": 1,
                    "Taxable": false,
                    "TaxInclusive": false,
                    "Name": "PI-0000000163",
                    "Currency": "USD",
                    "ModifiedById": "ddfec712-8827-4684-8287-1373e4f1f43d",
                    "ExternalId": "a3u3h000000LSKlAAO",
                    "ContractNumber": null,
                    "DisableSyncWithOpportunity": false,
                    "HasWildCards": false,
                    "DefaultQuantityDatasource": null,
                    "ProductId": "42157ac3-abb1-457e-88bb-4647144039e2",
                    "DefaultPriceFrom": null,
                    "DefaultPriceDatasource": null,
                    "PriceIncludedInBundle": false,
                    "AllocateGroupAdjustment": true,
                    "AutoRenewalType": null,
                    "MinMaxPriceAppliesTo": null,
                    "EnableCommitment": false,
                    "BillingRule": "Bill In Advance",
                    "EnableRampCreation": false,
                    "AutoRenewalTerm": 0,
                    "DisableCostModel": false,
                    "SubType": null,
                    "BillingFrequency": "One Time",
                    "RelatedAdjustmentAmount": 0,
                    "DefaultQuantityFrom": null,
                    "ContractItemNumber": null,
                    "DisableAssetIntegration": false,
                    "AllowPriceRampOverlap": false,
                    "PriceListId": "cbc75112-60e9-47b2-a632-f70d5912b70f",
                    "RelatedPercentAppliesTo": null,
                    "MaxPrice": null,
                    "RollupPriceToBundle": true,
                    "RelatedAdjustmentAmountSourceId": null,
                    "Description": null,
                    "AllowManualAdjustment": true,
                    "AutoRenew": false,
                    "MinUsageQuantity": 0,
                    "IsQuantityReadOnly": false,
                    "RelatedAdjustmentAppliesTo": null,
                    "Cost": null,
                    "MinPrice": null,
                    "AutoCascadeQuantity": false,
                    "MaxUsageQuantity": 0,
                    "AllowProration": false,
                    "HasCriteria": false,
                    "IsSellingTermReadOnly": false,
                    "RelatedPercent": null,
                    "RelatedAdjustmentType": null,
                    "Type": null,
                    "AutoCascadeSellingTerm": false,
                    "IsUsageTierModifiable": false
                }
            ],
            "ProductFeatureValues": null,
            "AssetLineItems": null,
            "ProductGroups": null,
            "ProductAttributeMatrixViews": null,
            "Translation": null,
            "CatAuto_Boolean_CstField_c": null,
            "CatAuto_Currency_CstField_c": null,
            "CatAuto_CustomFieldPickList_c": null,
            "CatAuto_DateTime_CstField_c": null,
            "CatAuto_Double_CstField_c": null,
            "CatAuto_Int_CstField_c": null,
            "CatAuto_Multipicklist_CstField_c": null,
            "CatAuto_String_CstField_c": null,
            "DisplayUrl": null,
            "ExcludeFromSitemap": false,
            "HasSearchAttributes": false,
            "IsCustomizable": false,
            "IsTabViewEnabled": false,
            "ProductType": null,
            "QuantityUnitOfMeasure": null,
            "RenewalLeadTime": 0,
            "StockKeepingUnit": null
        },
        "ProductOption": null,
        "ProductVersion": null,
        "Quantity": 1,
        "RelatedAdjustmentAmount": null,
        "RelatedAdjustmentAppliesTo": null,
        "RelatedAdjustmentType": null,
        "RelatedItem": null,
        "RelatedPercent": null,
        "RelatedPercentAppliesTo": null,
        "RenewalAdjustmentAmount": null,
        "RenewalAdjustmentType": null,
        "RollupPriceMethod": null,
        "RollupPriceToBundle": true,
        "SellingFrequency": "One Time",
        "SellingTerm": null,
        "SellingUom": null,
        "ServiceLocation": null,
        "ShipToAccount": null,
        "StartDate": null,
        "StatusDetails": null,
        "SummaryGroup": null,
        "SyncStatus": "Pending",
        "TaxCode": null,
        "Term": null,
        "TotalQuantity": null,
        "TransferPriceLineItem": null,
        "UnitCostAdjustment": null,
        "UnitPriceAdjustmentAuto": null,
        "UnitPriceAdjustmentManual": null,
        "Uom": "Each",
        "Currency": "USD",
        "Id": "02b215a2-2523-46c9-bbd9-3d9719991fcd",
        "Name": "DL380e Gen8 Entry Level",
        "CreatedBy": {
            "Id": "d717a075-9cbf-480c-b230-837e0e6dee75",
            "Name": "TestUser1 User"
        },
        "CreatedDate": "2022-09-20T08:48:58",
        "ModifiedBy": {
            "Id": "d717a075-9cbf-480c-b230-837e0e6dee75",
            "Name": "TestUser1 User"
        },
        "ModifiedDate": "2022-09-20T08:48:58",
        "ExternalId": "5ea23702"
    }
]